### ISSUE TITLE
Problem when using Leaflet

### ISSUE THREAD

**Issue by kylefelipe** [qgis2web/qgis2web#1010]
Qgis Version: 3.22.10-Białowieża  
qgis2web version: 3.26.0  
S.O: Linux Debian -  SID  
Python Version: 3.10.6  

Python Error:

```Shell
Traceback (most recent call last):
File "/home/kylefelipe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 190, in changeFormat
self.autoUpdatePreview()
File "/home/kylefelipe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 334, in autoUpdatePreview
self.previewMap()
File "/home/kylefelipe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 337, in previewMap
preview_file = self.createPreview()
File "/home/kylefelipe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 299, in createPreview
return writer.write(self.iface,
File "/home/kylefelipe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletWriter.py", line 90, in write
self.preview_file = self.writeLeaflet(
File "/home/kylefelipe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletWriter.py", line 261, in writeLeaflet
useOSMB) = writeVectorLayer(layer, safeLayerName,
File "/home/kylefelipe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletLayerScripts.py", line 128, in writeVectorLayer
(legend, symbol) = getLegend(layer, renderer, outputProjectFileName,
File "/home/kylefelipe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletLayerScripts.py", line 363, in getLegend
for cnt, c in enumerate(classes):
             UnboundLocalError: local variable 'classes' referenced before assignment
```
i'm getting this error right after click this button:

![image](https://user-images.githubusercontent.com/24795382/186554216-c225c393-b69a-4509-9643-e8a2ca59085a.png)

**Comment by boesiii** [comment]
Does the plugin work if you only use OpenLayers?

**Comment by boesiii** [comment]
My leaflet export works fine but it could be something in your layers causing the issue.  Try using the leaflet with one simple layer and see if you can narrow down the problem layer.  If you are still not able to find the issue please upload your QGIS project file and data or a sample of the data.

**Comment by onthego2003** [comment]
I'm having the same problem. I did as you suggested. I selected one layer at the time starting with the google satellite layer - preview worked fine. Added map layer preview worked fine. Added attribute table layer preview crashed with almost identical python errors as kelefelipe in leaflete view

**Comment by onthego2003** [comment]
update -it looks like a problem on Ubuntu operating system. tried it on Window 10 works just fine. My problem occurred when i upgraded to Jammy.

**Comment by onthego2003** [comment]
Update - I just tried again on a different Ubuntu machine with Jammy. Still the same problem. I did narrow it down to the symbol. I tried simple and it worked fine. However when I categorized the symbol, I got the python error "unexpected float"

**Comment by davechristianson** [comment]
Hello, I encountered a similar problem, regardless of whether I chose Leaflet or OpenLayers. The problem was with a single layer of polyline features.  Running 'Fix Geometries' on the layer resolved the issue in my case.
