### ISSUE TITLE
Plugin not working on Qt >= 5.6.

### ISSUE THREAD

**Issue by frida-161** [qgis2web/qgis2web#1019]
I tried to install the Plugin on a recent QGIS version with Qt 5.15. and I got the following Error:
```
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'


Python version: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] 
QGIS version: 3.28.2-Firenze Firenze, exported 
```

This is most likely caused by the QtWebKit Module being deprecated in recent Qt Versions (>= 5.6)
See this post: https://stackoverflow.com/questions/37876987/cannot-import-qtwebkitwidgets-in-pyqt5, the

**Comment by lukasschnellmann** [comment]
I tried to replicate it in an attempt to solve this issue but didn't succeed. I was using QGIS 3.32.3 on a Windows 10 version 22H2 system.

**Comment by tomchadwin** [comment]
QtWebKit has always been an issue. I can't remember the situation, but perhaps there is a version of Qt bundled with QGIS which includes QtWebKit? Is that rightm, @jef-n?

**Comment by jef-n** [comment]
Indeed.  QtWebKit is not part of Qt.  Debian and OSGeo4W have QtWebKit.

**Comment by towa** [comment]
As I understand it QtWebKit got removed in Qt 5.6 (see the stackoverflow post i linked).

I tested this on Arch Linux which ships a recend enough Qt for this to be a problem.

But I think for most people on Debian or OsGeo4W this should still work for a while. 

Just wanted to raise the issue because at some point QtWebKit will be missing there as well (with recend enough Qt).

**Comment by tomchadwin** [comment]
Thanks, @jef-n. SO it's been an issue for years, but we get away with it, because it's still available on a wide range of platforms. But by no means all, sadly. I looked at migrating to QtWebEngine some years ago, but there wasn't feature parity. Might be worth another investigation.

**Comment by andreaordonselli** [comment]
In addition to the test that I asked you in the previous message (referring to the exclusion of QtWebKit and therefore the plugin preview), I ask you to perform a test with [this file](https://github.com/tomchadwin/qgis2web/files/13476249/maindialog.zip) that I attach in which I replaced the use of QtWebKit with QtWebEngine, which is activated only if QtWebEngine is present, otherwise QtWebKit remains in operation.
Thank you.

**Comment by max-mapper** [comment]
@andreaordonselli I replaced the two files in file_with_edit and that fixed the plugin loading error for me and I am able to export maps and view them. 

However when I undo the changes from file_with_edit and just apply maindialog.zip, I receive the same loading error:

```
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets' 
Traceback (most recent call last):
  File "/home/max/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 62, in 
    from qgis.PyQt.QtWebEngineWidgets import QWebEngineView, QWebEngineSettings
  File "/usr/lib/python3.11/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by max-mapper** [comment]
Yes I am on Arch Linux

```
Python version: 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801] 
QGIS version: 3.34.0-Prizren Prizren, exported 
```

**Comment by markstos** [comment]
@max-mapper The error you are experiencing can be solved on Arch Linux by installing the "python-pyqt5-webkit" package from the AUR. On my machine, it takes about an hour to compile. 

But then, all of QGIS crashed when I tried to run the plugin. The crash seemed like it might be Wayland-related, so I forced to QGIS to run under XWayland checked that it was actually doing so. Still, running the plugin causes QGIS 3.34.1 to crash:

```
❯ env QT_QPA_PLATFORM=xcb qgis
ERROR 1: libarrow.so.1400: cannot open shared object file: No such file or directory
ERROR 1: libarrow.so.1400: cannot open shared object file: No such file or directory
ERROR 1: libarrow_dataset.so.1400: cannot open shared object file: No such file or directory
ERROR 1: libarrow_dataset.so.1400: cannot open shared object file: No such file or directory
ERROR 1: libarrow.so.1400: cannot open shared object file: No such file or directory
ERROR 1: libarrow.so.1400: cannot open shared object file: No such file or directory
ERROR 1: libarrow_dataset.so.1400: cannot open shared object file: No such file or directory
ERROR 1: libarrow_dataset.so.1400: cannot open shared object file: No such file or directory
Warning: QObject::connect: No such signal QWebPage::loadProgress(int)
Warning: QObject::connect: No such signal QWebPage::loadProgress(int)
Warning: QObject::connect: No such signal QWebFrame::titleChanged(QString)
Warning: QMetaObject::invokeMethod: No such method WebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method WebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method WebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method WebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method WebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method WebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method WebPage::repaintRequested(QRect)
Warning: QObject::connect: No such signal QWebFrame::titleChanged(QString)
Warning: QObject::connect: No such signal QWebFrame::iconChanged()
Warning: QObject::connect: No such signal QWebFrame::urlChanged(QUrl)
Warning: QObject::connect: No such signal WebPage::loadStarted()
Warning: QObject::connect: No such signal WebPage::loadProgress(int)
Warning: QObject::connect: No such signal WebPage::statusBarMessage(QString)
Warning: QObject::connect: No such signal WebPage::linkClicked(QUrl)
Warning: QObject::connect: No such signal WebPage::selectionChanged()
Warning: QObject::connect: No such signal WebPage::microFocusChanged()
QGIS died on signal 11ptrace: Operation not permitted.
No thread selected
No stack.
gdb returned 256
```

I now there are some errors about "libarrow". I'll see if I can solve those.

**Comment by markstos** [comment]
I solved the libarrow errors by installing the `python-pyarrow` package (which in turn installs the `arrow` package as a dependency. 

But launching the plugin still crashes QGIS with the same other warnings:

```
❯ env QT_QPA_PLATFORM=xcb qgis
Warning: QObject::connect: No such signal QWebPage::loadProgress(int)
Warning: QObject::connect: No such signal QWebPage::loadProgress(int)
Warning: QObject::connect: No such signal QWebFrame::titleChanged(QString)
Warning: QMetaObject::invokeMethod: No such method WebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method WebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method WebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method WebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method WebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method WebPage::repaintRequested(QRect)
Warning: QMetaObject::invokeMethod: No such method WebPage::repaintRequested(QRect)
Warning: QObject::connect: No such signal QWebFrame::titleChanged(QString)
Warning: QObject::connect: No such signal QWebFrame::iconChanged()
Warning: QObject::connect: No such signal QWebFrame::urlChanged(QUrl)
Warning: QObject::connect: No such signal WebPage::loadStarted()
Warning: QObject::connect: No such signal WebPage::loadProgress(int)
Warning: QObject::connect: No such signal WebPage::statusBarMessage(QString)
Warning: QObject::connect: No such signal WebPage::linkClicked(QUrl)
Warning: QObject::connect: No such signal WebPage::selectionChanged()
Warning: QObject::connect: No such signal WebPage::microFocusChanged()
QGIS died on signal 11ptrace: Operation not permitted.
No thread selected
No stack.
gdb returned 256
```

**Comment by markstos** [comment]
I got a little further by disabling all my layers except for one, which happened to be heatmap layer. QGIS still crashed, but with a different stack trace:

```
2023-12-20T21:09:31     WARNING    Traceback (most recent call last):
              File "/home/mark/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/qgis2web.py", line 59, in run
              self.dlg = MainDialog(self.iface)
              ^^^^^^^^^^^^^^^^^^^^^^
              File "/home/mark/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 159, in __init__
              self.autoUpdatePreview()
              File "/home/mark/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 334, in autoUpdatePreview
              self.previewMap()
              File "/home/mark/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 337, in previewMap
              preview_file = self.createPreview()
              ^^^^^^^^^^^^^^^^^^^^
              File "/home/mark/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 299, in createPreview
              return writer.write(self.iface,
              ^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/mark/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 81, in write
              self.preview_file = self.writeOL(iface, feedback,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/mark/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 134, in writeOL
              osmb = writeLayersAndGroups(layers, groups, visible, interactive,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/mark/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olLayerScripts.py", line 46, in writeLayersAndGroups
              (layerVar,
             TypeError: cannot unpack non-iterable NoneType object
             
```

**Comment by andreaordonselli** [comment]
Thanks @markstos for your tests.
I need  help to replicate the problem. In my Arch Linux 6.6.67-arch1-1 test machine with QGIS 3.28.9 Firenze installed with Qt 5.15.8, qgis2web latest version 3.17.2 works fine with QtWebKit. Why doesn't it work for you?
I have installed QGIS from the gnome GUI package manager. Here are the system screens and the working preview.
![2023-12-21 14_01_03-arch linux gnome  In esecuzione  - Oracle VM VirtualBox](https://github.com/qgis2web/qgis2web/assets/89784373/a6b5cf78-0aab-4409-94ba-0e53b5154447)

![2023-12-21 14_07_47-arch linux gnome  In esecuzione  - Oracle VM VirtualBox](https://github.com/qgis2web/qgis2web/assets/89784373/c902bf68-8a86-4b70-90bc-2514c5132eee)

![2023-12-22 12_39_11-arch linux gnome  In esecuzione  - Oracle VM VirtualBox](https://github.com/qgis2web/qgis2web/assets/89784373/32285dd7-1ed9-4cc1-bd87-f628837a9bbc)

**Comment by markstos** [comment]
I tried a simpler test of only loading a basic GeoJSON file before trying the plugin but still get a crash whether I launch GQIS in Wayland or XWayland. I have a Sway tool that lets me confirm which environment is used.
 
Here some details. 

 - I use Sway 1.8.
 - CPU: Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
 - Kernel: Linux 6.6.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 29 Nov 2023 00:37:40 +0000 x86_64 GNU/Linux
 - qgisweb: 3.17.2

QGIS details:
![image](https://github.com/qgis2web/qgis2web/assets/25829/6e30f05d-db9c-4552-8999-aeb6cd8c8753)

In `coredump list` I found that there was a coredump /  stacktrace for the crash. I've attached it. 
[qgis-stacktrace.txt](https://github.com/qgis2web/qgis2web/files/13759115/qgis-stacktrace.txt)

Next I'll try to launch QGIS with no customizations or plugins to sees if there's interference from another plugin.

**Comment by markstos** [comment]
I found my QGIS configuration was stored at `/home/mark/.local/share/QGIS`. I moved that aside to launch QGIS with no plugins or customizations and then re-installed `qgis2web`, opened a simple GeoJSON file and opened the `qgis2web`, but it still crashes in the same way. I made sure this was in an X11 session. So, interference with another plugin seems that it can be ruled out. 

Some other package versions:

* aur/python-pyqt5-webkit 5.15.10-1
* aur/qt5-webkit 5.212.0alpha4-21

**Comment by markstos** [comment]
I resolved my crashing problem by installing `qgis` using `conda`, which includes all the dependencies to make this work. 

I recommend simply not trying to support all Linux distros, but rather just list ones you support, and document that users of other distros are advised to install use QGIS via `conda`.

**Comment by Atreyagaurav** [comment]
Hi, which solution allows us to use it without preview? I am trying to use this on Arch Linux and the plugin doesn't work. I know not using The WebKit that's deprecated and moving to WebEngine might take time, but the solution where it won't preview and just export would be fine for now I think.

**Comment by markstos** [comment]
Have you tried installing QGIS with Conda?

*Mark Stosberg* (he/him)

Director of Systems & Security

***@***.*** | 765.277.1916

https://www.rideamigos.com <https://rideamigos.com/>

Changing the way the world commutes.


<https://www.linkedin.com/company/rideamigos>
<https://www.twitter.com/rideamigos> <https://www.facebook.com/rideamigos>
<https://www.instagram.com/rideamigos>
<https://rideamigos.com/newsletter-sign-up/>

**Comment by andreaordonselli** [comment]
Try following Mark's advice.  Otherwise you can try installing qgis2web v.3.16.1 and replace these 2 files 
[file_with_edit.zip](https://github.com/qgis2web/qgis2web/files/14089734/file_with_edit.zip)

**Comment by Atreyagaurav** [comment]
Replacing the files on the 3.16.1 worked. Thank you.

I do not want to install QGIS through conda as I don't use conda for anything else, and having to install conda and the whole QGIS for one plugin sounds a little too much. Specially as I have my own custom plugins and other problems might arise. And it won't be updated along with my other packages and I'm bound to forget I did something like that.

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which excluded WIKI and Preview functionality for Linux users who are unable to install and use QtWebKit, **so the plugin will launch and be usable without these features**

Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.

**Comment by andreaordonselli** [comment]
Hello, with the new release I have introduced QtwebEngine. Can you please test?
Thanks
https://github.com/qgis2web/qgis2web/releases/tag/v3.22.0
