### ISSUE TITLE
 qgis2web 3.18.2 crashs since QGIS v3.36.0 at Win & Mac

### ISSUE THREAD

**Issue by ITC-geoObserver** [qgis2web/qgis2web#1054]
Since QGIS version 3.36.0 (under Win & Mac) qgis2web (I use the latest v3.18.2) no longer works when vector data is included. The following error message appears:
--- begin error message -----------------

```
Creating OpenLayers map...
Exporting libraries... done
Exporting layers...
Exporting Baublöcke - Baublöcke Umrisse to JSON... done done
Exception in layer Baubl_cke___Baubl_cke_Umrisse_4d7baec7_fb30_4633_8b2c_d45503583c19 with renderer SINGLE: FILL SYMBOL (1 layers) color 141,16,18,255,rgb:0.55294117647058827,0.06274509803921569,0.07058823529411765,1: Traceback (most recent call last): File "C:\Users/myUser/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 47, in exportStyles useMapUnits) = singleSymbol(renderer, stylesFolder, File "C:\Users/myUser/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 213, in singleSymbol useMapUnits) = getSymbolAsStyle(symbol, stylesFolder, File "C:\Users/myUser/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 517, in getSymbolAsStyle color = getRGBAColor(props["line_color"], alpha) File "C:\Users/myUser/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 633, in getRGBAColor r, g, b, a = color.split(",") ValueError: too many values to unpack (expected 4) 
Writing HTML... done
Writing Layer Search... done
Success
Exported to C:\Users\myUser\AppData\Local\Temp\qgis2web
```

--- end error message -----------------

**Comment by andreaordonselli** [comment]
Yes, I'm aware of it, you can see this thread #1053 where the bug has already been fixed. You have 3 options: 

- download utils.py file from this repository and copy it into the plugin folder
- wait for new release (I think within a maximum of 2 weeks)
- download an older version of qgis (I recommend the latest LTR version)

_I kindly ask you to consider donating a coffee via the button on the homepage to support the development of qgis2web_
