### ISSUE TITLE
Unable to export with openlayers

### ISSUE THREAD

**Issue by flyisland** [qgis2web/qgis2web#1063]
## Versions
qgis: QGIS version 3.36.2-Maidenhead QGIS code revision 6d250527200
qgis2web: 3.19.0

Error wile exporting:
<img width="400" alt="image" src="https://github.com/qgis2web/qgis2web/assets/547085/3ac90ce9-856e-4f24-a944-15be34d7b0d0">

```
Creating OpenLayers map...
Exporting libraries... done
Exporting layers...
Exporting v6_time_pref_pgn_utf_wgs84.shp to JSON... done
Exporting 威海.tif as raster...
Exporting 威海.tif to PNG... done
Exporting 威海 to JSON... done done
Exception in layer v6_time_pref_pgn_utf_wgs84_shp_9d3058e7_2808_472d_a3eb_9a0e824d5aa3 with renderer SINGLE: FILL SYMBOL (1 layers) color 255,0,0,255,rgb:1,0,0,1: Traceback (most recent call last): File "/Users/ichen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 47, in exportStyles useMapUnits) = singleSymbol(renderer, stylesFolder, File "/Users/ichen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 213, in singleSymbol useMapUnits) = getSymbolAsStyle(symbol, stylesFolder, File "/Users/ichen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olStyleScripts.py", line 566, in getSymbolAsStyle color = getRGBAColor(props["color"], alpha) KeyError: 'color' 
Writing HTML... done
Writing Layer Search... done
Success
Exported to /private/tmp
```
Error on Chrome:
Only got a blank page with below error:
```
asserts.js:11 Uncaught AssertionError: Assertion failed. See https://openlayers.org/en/v6.4.3/doc/errors/#41 for details.
    at new e (AssertionError.js:36:24)
    at lt (asserts.js:11:15)
    at Style.js:379:13
    at e.setStyle (BaseVector.js:227:46)
    at e [as constructor] (BaseVector.js:121:15)
    at new e (Vector.js:35:23)
    at layers.js:10:43
```
<img width="731" alt="image" src="https://github.com/qgis2web/qgis2web/assets/547085/722a20c8-445e-4c05-a20d-344ed7f07312">

**Comment by andreaordonselli** [comment]
Can you attach your .qgz project and some example data in a zip?

**Comment by flyisland** [comment]
@andreaordonselli 
[seven.001.zip](https://github.com/qgis2web/qgis2web/files/15209885/seven.001.zip)

**Comment by flyisland** [comment]
[seven.002.zip](https://github.com/qgis2web/qgis2web/files/15209886/seven.002.zip)

**Comment by flyisland** [comment]
@andreaordonselli please change the above files to seven.zip.001 and seven.zip.002, then unzip them, thanks very much for your quick response

**Comment by andreaordonselli** [comment]
What gives error is the unsupported symbology of v6_time....
You could use this symbology to avoid export errors

![image](https://github.com/qgis2web/qgis2web/assets/89784373/9cf5e891-c6fb-466d-b606-aa4791a710c1)

Let me know if you can solve it with this method

**Comment by flyisland** [comment]
Hi @andreaordonselli, I changed the symbology of v6_time to "simple fill", the export works now, thanks.

But there are still two issues, 1)the labels of the "Waihai" contour are missing; 2) I used an expression to control the Stroke width of the "Waihai" contour, it seems that the exported web map doesn't support expression.

Do we have a support or un-support feature list?

**Comment by andreaordonselli** [comment]
Yes, in WIKI there are supported feature list:

https://qgis2web.github.io/qgis2web/#setLayers

https://qgis2web.github.io/qgis2web/#setLabels

The expressions are not supported for example.  I'll see if I can provide you with code for repeating the label along the perimeter.

**Comment by andreaordonselli** [comment]
For the labels I have to work on it, for the line stroke you could create a new field where you place the expression result values ​​and theme the stroke based on these

![image](https://github.com/qgis2web/qgis2web/assets/89784373/bc8a7275-c419-410d-93da-1ba9b874d6c3)

Then

![image](https://github.com/qgis2web/qgis2web/assets/89784373/c1e072e4-302a-4e79-a011-7ba9e5338278)

**Comment by flyisland** [comment]
The solution of "replacing expression with a new field" works, thanks!

**Comment by andreaordonselli** [comment]
As for the labels, I can't understand why if I use your project the export doesn't show the labels.
If instead I copy all the multilines of "Waihai" into a new linear vector layer, and export, the labels are visible.

Add this code to the bottom of the "Waihai" style file located in the "styles" folder of the export

```javascript
    var interval = 1200;
    var geometry = feature.getGeometry();
    if (geometry.getType() === 'MultiLineString') {
      geometry.getLineStrings().forEach(function (line) {
        var length = line.getLength();
        var intervals = Math.ceil(length / (interval * resolution));
        for (let i = 1; i < intervals; ++i) { //will not place labels at the start and end of the line
     // for (let i = 0; i <= intervals; ++i) to include them	
          var point = line.getCoordinateAt(i / intervals);
          var styletext = new ol.style.Style({
            text: new ol.style.Text({
              text: labelText,
              font: labelFont,
              fill: new ol.style.Fill({
                color: labelFill
              }),
              stroke: new ol.style.Stroke({
                color: bufferColor, 
                width: bufferWidth
              }),
            })
         });
          styletext.setGeometry(new ol.geom.Point(point));
          style.push(styletext);
        }
      });
    }
```

Here:
![image](https://github.com/qgis2web/qgis2web/assets/89784373/f6efe3fc-5e07-478e-a08a-710c30a0be11)



The result will show the labels repeated along the linestring, adjust "var interval" with the necessary value

![image](https://github.com/qgis2web/qgis2web/assets/89784373/2ea21bc4-bc5a-43c8-a8d0-bc1b57f56626)

**Comment by flyisland** [comment]
@andreaordonselli thanks, I'll try if I could apply your solution in my project

**Comment by andreaordonselli** [comment]
You're welcome.  If you are happy with qgis2web I kindly ask you to consider donating a virtual coffee via the button on the home page to support the development of the project, thank you.

**Comment by omerskar** [comment]
Hello, first of all, thank you for developing qgis2web. I wanted to use the application to publish my project as a web map. My map contains the zoning styles I prepared and therefore the map is exported empty as discussed here before. Do you plan to develop the code and algorithm needed to export custom styles? I will share my style file if necessary. Thank you.

Note: I have already donated a small cup of virtual coffee.

![image](https://github.com/user-attachments/assets/d12f8570-a72b-4f22-b189-9d57ed6309d0)

**Comment by andreaordonselli** [comment]
From the photo I notice that your styles are too complex to be exported. Keep in mind that it is very complicated to export "not simple" styles. Can you attach your project?
There is a way to trick the style through Sldreader, but I have to do some tests.

**Comment by omerskar** [comment]
Thank you for you interest. I am waiting good news reagarding this issue.

[Sazlibosna.zip](https://github.com/user-attachments/files/18290877/Sazlibosna.zip)

**Comment by andreaordonselli** [comment]
Instead of using the style exported by qgis2web to color the layer, I've exported the style from QGIS in SLD format and used the `sldreader.js` library to color the layer; unfortunately, even doing so, this is the result:

![image](https://github.com/user-attachments/assets/20f1e9e6-a443-4ae9-bb51-52c9aed82c63)

As you can see, it is equivalent to using non-complex symbols in QGIS and exporting with qgis2web or qgis2o.gis without relying on external libraries.
There are no existing alternatives except installing QGIS Server on a separate machine, configuring it to read the project's .qgz file, and setting up the database, viewer, etc., which are more complex tasks.
I recommend simplifying your symbology; in interactive web maps, they are often not as essential as they are in print layouts.

**Comment by omerskar** [comment]
Thank you for your effort. Of course, interactive web maps symbology should be simpler than the hard copy or desktop application view. Also, I have already designed a web map with simple symbology. I just tried to export it to a web map with complex symbology via qgis2web, I got some errors during processing. I found this issue on GitHub while trying to find a solution. The reason I asked you is because you are a qgis2web developer. Thank you again and please follow the web map link below.

[https://kargismap.com/wp-content/plugins/gis-maps/gismaps_maps/Sazlibosna/](url)

**Comment by andreaordonselli** [comment]
Complimenti per la mappa, hai anche usato la trasparenza del colore.
