### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by valterhydrodynamics** [qgis2web/qgis2web#1065]
To ensure no time or effort is wasted in bug reporting, please follow these steps:

1. Make sure you are using the latest release of qgis2web - yes;
2. Check the issues on Github to see whether the bug has already been reported, and if so, read through all the comments on the issue, and add any additional information from your experience of the bug - did not find it;
3. Make sure you can reproduce the bug reliably - yes;
4. Reduce the complexity of your bug conditions as far as you can, especially by reducing the number of layers, ideally to one - 2 layers;
5. Raise a Github issue, including:
  - only one bug per Github issue - OK;
  - the qgis2web version (or make it clear you are using Github master branch) - latest installed with "Plugins\Manage and Install Plugins";
  - any Python error text/stack trace which occurs - bellow:
 //
2024-05-11T15:01:25     WARNING    Traceback (most recent call last):
              File "C:\Users/Valter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\qgis2web.py", line 59, in run
              self.dlg = MainDialog(self.iface)
              ^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Valter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 179, in __init__
              self.autoUpdatePreview()
              File "C:\Users/Valter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 369, in autoUpdatePreview
              self.previewMap()
              File "C:\Users/Valter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 372, in previewMap
              preview_file = self.createPreview()
              ^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Valter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 334, in createPreview
              return writer.write(self.iface,
              ^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Valter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 81, in write
              self.preview_file = self.writeOL(iface, feedback,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Valter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 182, in writeOL
              grid = getGrid(project)
              ^^^^^^^^^^^^^^^^
              File "C:\Users/Valter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olScriptStrings.py", line 678, in getGrid
              props = layer["prop"]
              ~~~~~^^^^^^^^
             KeyError: 'prop'
 //
  - browser JS console errors - press F12 in qgis2web to open the developer toolbar and find the console
  - screenshot of your settings - bellow;
 ![Capturar](https://github.com/qgis2web/qgis2web/assets/43525314/5991b0bd-3d06-4715-9f80-49b0c0ae5262)
  - screenshot of the output - bellow;
 ![Capturar](https://github.com/qgis2web/qgis2web/assets/43525314/5991b0bd-3d06-4715-9f80-49b0c0ae5262)
  - a link to the data you used, if possible - gues it's not needed.

**Comment by andreaordonselli** [comment]
can you attach a zip containing your qgz project and data?  I can't understand the error.  What settings do you have in qgis2web?  does the plugin start but gives an error during export or does not start?

**Comment by valterhydrodynamics** [comment]
Will send it before as soon i arrive

**Comment by valterhydrodynamics** [comment]
No need to; guess it's some of the plugins installed.
Now opens "fast & furious".
Thanks for the quick reply.
![Capturar](https://github.com/qgis2web/qgis2web/assets/43525314/dbc6af46-fd73-4145-9309-5ed5b5d4bd93)

**Comment by andreaordonselli** [comment]
I'm glad your problem is solved.  Thank you for using qgis2web.  I kindly ask you to consider donating a virtual coffee via the button on the github home to support the development of the project.  Greetings.
