### ISSUE TITLE
SVG Marker Rotation Causes Error in Leaflet

### ISSUE THREAD

**Issue by ronsander** [qgis2web/qgis2web#1087]
I have a qgz project with symbology set to an SVG symbol. The rotation of the symbol is set to an azimuth field. When the project is exported to leaflet the following errors occur. The error does not occur when the symbols are not rotated. Setting the rotation to the azimuth field causes the error upon export. I'm not sure how to attach the gpkg and qgz files. Thanks for your help. qgis2web is a really cool program!

**Phthon Warning:**
2024-08-02T13:26:11     WARNING    warning:C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py:185: DeprecationWarning: QgsCoordinateReferenceSystem constructor is deprecated
              exp_crs = QgsCoordinateReferenceSystem(4326, crs)
             
             traceback: File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 225, in changeFormat
              self.autoUpdatePreview()
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 369, in autoUpdatePreview
              self.previewMap()
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 372, in previewMap
              preview_file = self.createPreview()
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 334, in createPreview
              return writer.write(self.iface,
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 94, in write
              self.preview_file = self.writeLeaflet(
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 185, in writeLeaflet
              exp_crs = QgsCoordinateReferenceSystem(4326, crs)
             
2024-08-02T13:26:11     WARNING    warning:C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py:220: DeprecationWarning: QgsCoordinateReferenceSystem.toProj4() is deprecated
              crsProj4 = crsSrc.toProj4()
             
             traceback: File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 225, in changeFormat
              self.autoUpdatePreview()
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 369, in autoUpdatePreview
              self.previewMap()
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 372, in previewMap
              preview_file = self.createPreview()
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 334, in createPreview
              return writer.write(self.iface,
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 94, in write
              self.preview_file = self.writeLeaflet(
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 220, in writeLeaflet
              crsProj4 = crsSrc.toProj4()
             
2024-08-02T13:26:11     WARNING    warning:C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py:228: DeprecationWarning: QgsCoordinateReferenceSystem constructor is deprecated
              crsDest = QgsCoordinateReferenceSystem(4326)
             
             traceback: File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 225, in changeFormat
              self.autoUpdatePreview()
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 369, in autoUpdatePreview
              self.previewMap()
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 372, in previewMap
              preview_file = self.createPreview()
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 334, in createPreview
              return writer.write(self.iface,
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 94, in write
              self.preview_file = self.writeLeaflet(
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 228, in writeLeaflet
              crsDest = QgsCoordinateReferenceSystem(4326)
             

Python Error:
2024-08-02T13:26:11     WARNING    Traceback (most recent call last):
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 225, in changeFormat
              self.autoUpdatePreview()
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 369, in autoUpdatePreview
              self.previewMap()
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 372, in previewMap
              preview_file = self.createPreview()
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 334, in createPreview
              return writer.write(self.iface,
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 94, in write
              self.preview_file = self.writeLeaflet(
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 276, in writeLeaflet
              useOSMB) = writeVectorLayer(layer, safeLayerName,
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletLayerScripts.py", line 125, in writeVectorLayer
              useShapes) = getLayerStyle(layer, safeLayerName, interactive,
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletStyleScripts.py", line 41, in getLayerStyle
              pattern) = getSymbolAsStyle(symbol, markerFolder,
              File "C:\Users/rsander/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletStyleScripts.py", line 216, in getSymbolAsStyle
              if symbol.dataDefinedAngle().useExpression():
             AttributeError: 'QgsProperty' object has no attribute 'useExpression'
             

Messages:
****2024-08-02T13:26:11     WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.

**qgis2web Version:**
![image](https://github.com/user-attachments/assets/dd4a0055-c0e0-457e-aa87-9ef725a1c1a1)

**Qgis Version:**
![image](https://github.com/user-attachments/assets/20e4250d-7ac7-4d4b-8783-19a1ff437c1b)

**Comment by andreaordonselli** [comment]
Sorry, SVG rotation is not supported yet. I will do it in the future. For now you will have to program it by hand. You can attach your project in a zip. QGZ and data.

**Comment by ronsander** [comment]
Thank you so much for letting me know. It’s fine without. It’s a great tool!


Ronald Sander
ms consultants, inc<http://www.msconsultants.com/> | engineers, planners
300 Corporate Center Drive, Suite 200, Moon Township, Pennsylvania 15108

p: 412-264-8701 Ext. 18173
e: ***@***.******@***.***>
Connect: Facebook<https://www.facebook.com/msconsultantsinc> | LinkedIn<https://www.linkedin.com/company/ms-consultants-inc-> | ms Blog<http://www.msconsultants.com/blog/>

***@***.***<http://www.msconsultants.com/>
Sign up to receive our email newsletter<https://msconsultants.us2.list-manage.com/subscribe?u=28f451827303d6db653f478fd&id=c549949275>

Notice of Confidentiality: **This e-mail and any of its attachments may contain proprietary information, which is privileged, confidential, or subject to copyright belonging to ms consultants, inc. This e-mail is intended solely for the use of the individual or entity to which it is addressed. If you are not the intended recipient of this e-mail, you are hereby notified that any dissemination, distribution, copying, or action taken in relation to the contents of and/or attachments to this e-mail is strictly prohibited and may be unlawful. If you have received this e-mail in error, please notify the sender immediately and permanently delete the original and any copy of this e-mail and any printout.**

**Comment by andreaordonselli** [comment]
Evaluate a donation via the Home button to support the project.
Many thanks.
