### ISSUE TITLE
leaflet lables only show the first one

### ISSUE THREAD

**Issue by liaozhengjun** [qgis2web/qgis2web#1095]
hello,I found lables only show the first one when trasfer to leaflet,but it's ok when transfer to openlayer.
vesiong:3.22.0
1、to openlayers:
![1725729284337](https://github.com/user-attachments/assets/7ca3da34-b719-48d3-9a07-36155e307092)

2、 to leaflet:
![image](https://github.com/user-attachments/assets/2a38b669-b768-4d3b-8fad-4e0623b176d5)

3: edge console:

Class.js:121  Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at file:///C:/Users/liaozhengjun/AppData/Local/Temp/qgis2web/qgis2web_2024_09_08-01_17_05_190983/js/leaflet.js:5:3170
    at S.extend (file:///C:/Users/liaozhengjun/AppData/Local/Temp/qgis2web/qgis2web_2024_09_08-01_17_05_190983/js/leaflet.js:5:3188)
    at file:///C:/Users/liaozhengjun/AppData/Local/Temp/qgis2web/qgis2web_2024_09_08-01_17_05_190983/js/leaflet.pattern.js:6:34
    at file:///C:/Users/liaozhengjun/AppData/Local/Temp/qgis2web/qgis2web_2024_09_08-01_17_05_190983/js/leaflet.pattern.js:6:7077
(匿名) @ Class.js:121
labels.js:30  Uncaught TypeError: Cannot read properties of undefined (reading '_container')
    at addLabel (labels.js:30:54)
    at index.html:277:15
    at i.eachLayer (LayerGroup.js:123:11)
    at index.html:268:18

**Comment by andreaordonselli** [comment]
Can you attach your project? I would like to check the data.

**Comment by liaozhengjun** [comment]
> Can you attach your project? I would like to check the data.
sure,it's just a test project.
[qgis2web_2024_09_08-01_48_46_130037.zip](https://github.com/user-attachments/files/16920451/qgis2web_2024_09_08-01_48_46_130037.zip)

**Comment by andreaordonselli** [comment]
I can't understand the problem, maybe Leaflet is having trouble reading particular characters in the data? Maybe an apostrophe or a parenthesis or an accent?

You should attach your qgis project with data, not export

**Comment by liaozhengjun** [comment]
> I can't understand the problem, maybe Leaflet is having trouble reading particular characters in the data? Maybe an apostrophe or a parenthesis or an accent?
> 
> You should attach your qgis project with data, not export
there is no  apostrophe or  parenthesis ,it's just aaa bbb and ccc ,when transfer to leaflet ,only show the aaa, bbb and ccc not show.
![image](https://github.com/user-attachments/assets/746518ca-2b54-4945-8f06-edd6a1173fa9)


[test01.zip](https://github.com/user-attachments/files/16932696/test01.zip)

**Comment by andreaordonselli** [comment]
Leaflet turns off the labels that overlap with other labels, by zooming in the others will appear

**Comment by liaozhengjun** [comment]
> Leaflet turns off the labels that overlap with other labels, by zooming in the others will appear


I dont understand ,no matter how i zomm it ,it does not appear.
so it is really not a error in edge？

![image](https://github.com/user-attachments/assets/052886fc-c9b6-40e3-b17f-f18eca92c4f8)

**Comment by liaozhengjun** [comment]
> The example project you loaded was just the qgz, not the data. So in my tests I created a point layer. I think it's a problem at your level. Can you send me qgz and your data? The Edge error shows that there is something wrong with the labels but I can't reproduce your problem.

Actually, I just created a layer of three points without any other data, if this is the data you need.

![image](https://github.com/user-attachments/assets/beb404f8-72ee-4f4a-9649-1a383ca6c02b)

**Comment by liaozhengjun** [comment]
> qgz
or this data ?
[test01.zip](https://github.com/user-attachments/files/16943477/test01.zip)

**Comment by liaozhengjun** [comment]
I have found the reason：If I create a layer of type Point (Point), there will be no problem. If I create a layer of type Point (MultiPoint), there will be an issue where labels cannot be displayed.

**Comment by andreaordonselli** [comment]
You're right, I'll look into the matter, thanks for reporting

**Comment by liaozhengjun** [comment]
> You're right, I'll look into the matter, thanks for reporting

My pleasure，Thank you for your following.
