### ISSUE TITLE
ValueError: could not convert string to float: 'geoStyle(4.0)' [UNSOLVED - unable to reproduce the problem]

### ISSUE THREAD

**Issue by angelesbri1s** [qgis2web/qgis2web#1097]
When exporting to map to web using the lastest version (3.22.0) of the plugin, I get this error:

```
An error has occurred while executing Python code: 

ValueError: could not convert string to float: 'geoStyle(4.0)' 
Traceback (most recent call last):
  File "/Users/mycomputer/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 505, in saveMap
    results = writer.write(self.iface,
  File "/Users/mycomputer/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletWriter.py", line 94, in write
    self.preview_file = self.writeLeaflet(
  File "/Users/mycomputer/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletWriter.py", line 276, in writeLeaflet
    useOSMB) = writeVectorLayer(layer, safeLayerName,
  File "/Users/mycomputer/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletLayerScripts.py", line 125, in writeVectorLayer
    useShapes) = getLayerStyle(layer, safeLayerName, interactive,
  File "/Users/mycomputer/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletStyleScripts.py", line 41, in getLayerStyle
    pattern) = getSymbolAsStyle(symbol, markerFolder,
  File "/Users/mycomputer/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletStyleScripts.py", line 253, in getSymbolAsStyle
    style, useMapUnits = getStrokeStyle(color, line_style, line_width,
  File "/Users/mycomputer/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletStyleScripts.py", line 358, in getStrokeStyle
    dash_length = 4 * float(width)
ValueError: could not convert string to float: 'geoStyle(4.0)'


Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS version: 3.38.2-Grenoble Grenoble, 130c432394e 

Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/mycomputer/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/mycomputer/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Users/mycomputer/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/mycomputer/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Users/mycomputer/Documents/myProject
```
I am using iOS sonoma 14.4.1 and this are my QGis settings:

<img width="875" alt="Screenshot 2024-09-08 at 17 50 04" src="https://github.com/user-attachments/assets/da0cac48-977a-4da4-a6b5-57bd46757fee">

**Comment by andreaordonselli** [comment]
Can you upload an example of your project to reproduce the problem?
Thanks

**Comment by angelesbri1s** [comment]
Unfortunately, I can't upload the example (sensible data I can't disclose). Is there any other material that can help you understand my problem?
I uninstalled the plugin and then installed it again. The problem remains.

**Comment by andreaordonselli** [comment]
Simplify symbols to the maximum; use only single, categorized or graduated symbols.
Make sure the layer field names don't have any odd characters; for example "geoStyle(4.0)" it seems to give problems (maybe you have to eliminate the brackets, or the point).
Layer names must also be simple.
Take these first tests and try to export.

**Comment by angelesbri1s** [comment]
Thanks, @andreaordonselli , for the quick reply. I created a new project from scratch to check if there was a problem with my computer with the plugin or a project problem. The latest project runs correctly, so as you suggested, my project has a problem (using map units as a measure for symbols breaks everything). Now I am encountering other problems: QGis unexpectedly closes when exporting using Leaflet (with OpenLayers is ok); the HTML is not exported into the folder; the filters are not exported. I will look into the previous issues.

**Comment by andreaordonselli** [comment]
Simplifying the project always helps us understand the origin of the problem.
Regarding the Leaflet export I believe the QGIS crash error is related to symbolLayerCount(), can you read the first few lines of the error to confirm?

If that's the case, I've already asked the QGIS developers why this is happening. With the previous version 3.36 the error does not occur, however with this version of QGIS you will not have the preview. If this is the problem you could consider working with QGIS v3.36 and doing without the preview until I clarify the problem.

Let me know.
