### ISSUE TITLE
Wont Generate Leaflet Map

### ISSUE THREAD

**Issue by radenblazed** [qgis2web/qgis2web#1113]
When i try to generate a web map I get an error, it generates some files and folders but it does not generate a working map. I tried it on both windows 10 and Ubuntu. I asked around in the community for a fix but could get no help, some people told me it was a plugin bug and that i should report it that's why Im posting it here. First time posting an Issue, so sorry if Im not doing it right lol. If any more info is needed just let me know and I will follow up. As far as the settings go, Im using the default settings for the plugin just as they came.

Windows 10 QGIS = 3.40
Windows 10 qgis2web = 3.23.0

```
 An error has occurred while executing Python code:


FileNotFoundError: [Errno 2] No such file or directory: 'base64:PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB2aWV3Qm94PSIwIDAgMTUgMTUiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+CiAgPHBhdGggZmlsbD0icGFyYW0oZmlsbCkgIzAwMCIgZmlsbC1vcGFjaXR5PSJwYXJhbShmaWxsLW9wYWNpdHkpIiBzdHJva2U9InBhcmFtKG91dGxpbmUpICNmZmYiIHN0cm9rZS13aWR0aD0icGFyYW0ob3V0bGluZS13aWR0aCkgMCIgc3Ryb2tlLW9wYWNpdHk9InBhcmFtKG91dGxpbmUtb3BhY2l0eSkiIGQ9Ik0yIDFMMy43NSAxQzMuOTEgMSA0LjA2IDEuMDcgNC4xNSAxLjJMNyA1TDYgMTBMOSAxMkw5LjgyIDEzLjY0QzkuODggMTMuNzYgOS44MyAxMy45MSA5LjcxIDEzLjk3QzkuNjcgMTMuOTkgOS42MyAxNCA5LjYgMTRMMiAxNEMxLjQ1IDE0IDEgMTMuNTUgMSAxM0wxIDJDMSAxLjQ1IDEuNDUgMSAyIDFaTTkuNDMgNS4wM0wxMS42OCA1Ljc4QzExLjgzIDUuODMgMTEuOTUgNS45NCAxMiA2LjA5TDEyLjc2IDguMzhDMTIuODUgOC42NCAxMi43MSA4LjkzIDEyLjQ0IDkuMDFMMTAuMTEgOS43OUM5Ljk5IDkuODMgOS44NSA5LjgyIDkuNzMgOS43Nkw4LjI4IDkuMDNDOC4wNyA4LjkzIDcuOTYgOC42OSA4LjAxIDguNDdMOC43OSA1LjM4QzguODUgNS4xMSA5LjEzIDQuOTUgOS4zOSA1LjAyQzkuNDEgNS4wMiA5LjQyIDUuMDIgOS40MyA1LjAzWk0xMSAxMi4zM0wxMSAxMS4xNEMxMSAxMC45NSAxMS4xMSAxMC43OCAxMS4yOCAxMC42OUwxMi42MyAxMC4wMkMxMi44NCA5LjkxIDEzLjExIDkuOTcgMTMuMjUgMTAuMTZMMTQuMTggMTEuNDFDMTQuMzUgMTEuNjMgMTQuMyAxMS45NCAxNC4wOCAxMi4xMUMxNC4wOCAxMi4xMSAxNC4wNyAxMi4xMiAxNC4wNiAxMi4xMkwxMy4xMyAxMi43NUMxMy4wNCAxMi44IDEyLjk1IDEyLjgzIDEyLjg1IDEyLjgzTDExLjUgMTIuODNDMTEuMjIgMTIuODMgMTEgMTIuNjEgMTEgMTIuMzNaIi8+Cjwvc3ZnPg=='

Traceback (most recent call last):

File "C:\Users/raden/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 496, in saveMap

results = writer.write(self.iface,

^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users/raden/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 94, in write

self.preview_file = self.writeLeaflet(

^^^^^^^^^^^^^^^^^^

File "C:\Users/raden/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 277, in writeLeaflet

useOSMB) = writeVectorLayer(layer, safeLayerName,

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users/raden/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletLayerScripts.py", line 125, in writeVectorLayer

useShapes) = getLayerStyle(layer, safeLayerName, interactive,

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users/raden/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletStyleScripts.py", line 41, in getLayerStyle

pattern) = getSymbolAsStyle(symbol, markerFolder,

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users/raden/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletStyleScripts.py", line 235, in getSymbolAsStyle

with open(sl.path()) as f:

^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: 'base64:PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB2aWV3Qm94PSIwIDAgMTUgMTUiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+CiAgPHBhdGggZmlsbD0icGFyYW0oZmlsbCkgIzAwMCIgZmlsbC1vcGFjaXR5PSJwYXJhbShmaWxsLW9wYWNpdHkpIiBzdHJva2U9InBhcmFtKG91dGxpbmUpICNmZmYiIHN0cm9rZS13aWR0aD0icGFyYW0ob3V0bGluZS13aWR0aCkgMCIgc3Ryb2tlLW9wYWNpdHk9InBhcmFtKG91dGxpbmUtb3BhY2l0eSkiIGQ9Ik0yIDFMMy43NSAxQzMuOTEgMSA0LjA2IDEuMDcgNC4xNSAxLjJMNyA1TDYgMTBMOSAxMkw5LjgyIDEzLjY0QzkuODggMTMuNzYgOS44MyAxMy45MSA5LjcxIDEzLjk3QzkuNjcgMTMuOTkgOS42MyAxNCA5LjYgMTRMMiAxNEMxLjQ1IDE0IDEgMTMuNTUgMSAxM0wxIDJDMSAxLjQ1IDEuNDUgMSAyIDFaTTkuNDMgNS4wM0wxMS42OCA1Ljc4QzExLjgzIDUuODMgMTEuOTUgNS45NCAxMiA2LjA5TDEyLjc2IDguMzhDMTIuODUgOC42NCAxMi43MSA4LjkzIDEyLjQ0IDkuMDFMMTAuMTEgOS43OUM5Ljk5IDkuODMgOS44NSA5LjgyIDkuNzMgOS43Nkw4LjI4IDkuMDNDOC4wNyA4LjkzIDcuOTYgOC42OSA4LjAxIDguNDdMOC43OSA1LjM4QzguODUgNS4xMSA5LjEzIDQuOTUgOS4zOSA1LjAyQzkuNDEgNS4wMiA5LjQyIDUuMDIgOS40MyA1LjAzWk0xMSAxMi4zM0wxMSAxMS4xNEMxMSAxMC45NSAxMS4xMSAxMC43OCAxMS4yOCAxMC42OUwxMi42MyAxMC4wMkMxMi44NCA5LjkxIDEzLjExIDkuOTcgMTMuMjUgMTAuMTZMMTQuMTggMTEuNDFDMTQuMzUgMTEuNjMgMTQuMyAxMS45NCAxNC4wOCAxMi4xMUMxNC4wOCAxMi4xMSAxNC4wNyAxMi4xMiAxNC4wNiAxMi4xMkwxMy4xMyAxMi43NUMxMy4wNCAxMi44IDEyLjk1IDEyLjgzIDEyLjg1IDEyLjgzTDExLjUgMTIuODNDMTEuMjIgMTIuODMgMTEgMTIuNjEgMTEgMTIuMzNaIi8+Cjwvc3ZnPg=='

Python version: 3.12.7 (main, Oct 25 2024, 11:18:09) [MSC v.1938 64 bit (AMD64)]

QGIS version: 3.40.0-Bratislava Bratislava, b56115d874

Python Path:

S:/Program Files/QGIS Mapeditor/apps/qgis/./python

C:/Users/raden/AppData/Roaming/QGIS/QGIS3\profiles\default/python

C:/Users/raden/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins

S:/Program Files/QGIS Mapeditor/apps/qgis/./python/plugins

S:\Program Files\QGIS Mapeditor\apps\grass\grass84\etc\python

C:\Users\raden\Documents

S:\Program Files\QGIS Mapeditor\bin\python312.zip

S:\Program Files\QGIS Mapeditor\apps\Python312\DLLs

S:\Program Files\QGIS Mapeditor\apps\Python312\Lib

S:\Program Files\QGIS Mapeditor\bin

C:\Users\raden\AppData\Roaming\Python\Python312\site-packages

S:\Program Files\QGIS Mapeditor\apps\Python312

S:\Program Files\QGIS Mapeditor\apps\Python312\Lib\site-packages

S:\Program Files\QGIS Mapeditor\apps\Python312\Lib\site-packages\win32

S:\Program Files\QGIS Mapeditor\apps\Python312\Lib\site-packages\win32\lib

S:\Program Files\QGIS Mapeditor\apps\Python312\Lib\site-packages\Pythonwin

C:/Users/raden/AppData/Roaming/QGIS/QGIS3\profiles\default/python

C:\Users\raden\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

E:/RadenBlazed/Gaming/AoC/QGIS/QGIS Projects/AoCmap-1 
```

I tried running it on ubuntu to see if it would work, but I end up getting a similar error.

Ubuntu QGIS = 3.40
Ubuntu qgis2web = 3.23.0

```
An error has occurred while executing Python code: 

OSError: [Errno 36] File name too long: 'base64:PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJnYXJkZW4iIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjE1IiBoZWlnaHQ9IjE1IiB2aWV3Qm94PSIwIDAgMTUgMTUiPgogIDxwYXRoIGZpbGw9InBhcmFtKGZpbGwpICMwMDAiIGZpbGwtb3BhY2l0eT0icGFyYW0oZmlsbC1vcGFjaXR5KSIgc3Ryb2tlPSJwYXJhbShvdXRsaW5lKSAjZmZmIiBzdHJva2Utd2lkdGg9InBhcmFtKG91dGxpbmUtd2lkdGgpIDAiIHN0cm9rZS1vcGFjaXR5PSJwYXJhbShvdXRsaW5lLW9wYWNpdHkpIiBkPSJNMTMsOGMwLDMuMzEtMi4xOSw2LTUuNSw2UzIsMTEuMzEsMiw4YzIuMjY0MywwLjAxOTEsNC4yNjk0LDEuNDY2Nyw1LDMuNjFWN0g0LjVDMy42NzE2LDcsMyw2LjMyODQsMyw1LjV2LTMmI3hBOyYjeDk7QzMsMi4yMjM5LDMuMjIzOSwyLDMuNSwyYzAuMTU3NCwwLDAuMzA1NiwwLjA3NDEsMC40LDAuMmwxLjUzLDJsMS42NS0zYzAuMTQ5OC0wLjIzMiwwLjQ1OTMtMC4yOTg1LDAuNjkxMy0wLjE0ODcmI3hBOyYjeDk7QzcuODMwOCwxLjA4OTgsNy44ODE1LDEuMTQwNCw3LjkyLDEuMmwxLjY1LDNsMS41My0yYzAuMTY1Ny0wLjIyMDksMC40NzkxLTAuMjY1NywwLjctMC4xQzExLjkyNTksMi4xOTQ0LDEyLDIuMzQyNiwxMiwyLjV2MyYjeEE7JiN4OTtDMTIsNi4zMjg0LDExLjMyODQsNywxMC41LDdIOHY0LjYxQzguNzMwNiw5LjQ2NjcsMTAuNzM1Nyw4LjAxOTEsMTMsOHoiLz4KPC9zdmc+' 
Traceback (most recent call last):
  File "/home/raden/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 496, in saveMap
    results = writer.write(self.iface,
  File "/home/raden/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletWriter.py", line 94, in write
    self.preview_file = self.writeLeaflet(
  File "/home/raden/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletWriter.py", line 277, in writeLeaflet
    useOSMB) = writeVectorLayer(layer, safeLayerName,
  File "/home/raden/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletLayerScripts.py", line 125, in writeVectorLayer
    useShapes) = getLayerStyle(layer, safeLayerName, interactive,
  File "/home/raden/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletStyleScripts.py", line 41, in getLayerStyle
    pattern) = getSymbolAsStyle(symbol, markerFolder,
  File "/home/raden/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletStyleScripts.py", line 235, in getSymbolAsStyle
    with open(sl.path()) as f:
OSError: [Errno 36] File name too long: 'base64:PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJnYXJkZW4iIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjE1IiBoZWlnaHQ9IjE1IiB2aWV3Qm94PSIwIDAgMTUgMTUiPgogIDxwYXRoIGZpbGw9InBhcmFtKGZpbGwpICMwMDAiIGZpbGwtb3BhY2l0eT0icGFyYW0oZmlsbC1vcGFjaXR5KSIgc3Ryb2tlPSJwYXJhbShvdXRsaW5lKSAjZmZmIiBzdHJva2Utd2lkdGg9InBhcmFtKG91dGxpbmUtd2lkdGgpIDAiIHN0cm9rZS1vcGFjaXR5PSJwYXJhbShvdXRsaW5lLW9wYWNpdHkpIiBkPSJNMTMsOGMwLDMuMzEtMi4xOSw2LTUuNSw2UzIsMTEuMzEsMiw4YzIuMjY0MywwLjAxOTEsNC4yNjk0LDEuNDY2Nyw1LDMuNjFWN0g0LjVDMy42NzE2LDcsMyw2LjMyODQsMyw1LjV2LTMmI3hBOyYjeDk7QzMsMi4yMjM5LDMuMjIzOSwyLDMuNSwyYzAuMTU3NCwwLDAuMzA1NiwwLjA3NDEsMC40LDAuMmwxLjUzLDJsMS42NS0zYzAuMTQ5OC0wLjIzMiwwLjQ1OTMtMC4yOTg1LDAuNjkxMy0wLjE0ODcmI3hBOyYjeDk7QzcuODMwOCwxLjA4OTgsNy44ODE1LDEuMTQwNCw3LjkyLDEuMmwxLjY1LDNsMS41My0yYzAuMTY1Ny0wLjIyMDksMC40NzkxLTAuMjY1NywwLjctMC4xQzExLjkyNTksMi4xOTQ0LDEyLDIuMzQyNiwxMiwyLjV2MyYjeEE7JiN4OTtDMTIsNi4zMjg0LDExLjMyODQsNywxMC41LDdIOHY0LjYxQzguNzMwNiw5LjQ2NjcsMTAuNzM1Nyw4LjAxOTEsMTMsOHoiLz4KPC9zdmc+'


Python version: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] 
QGIS version: 3.40.0-Bratislava Bratislava, b56115d8743 

Python Path:
/usr/share/qgis/python
/home/raden/.local/share/QGIS/QGIS3/profiles/default/python
/home/raden/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/raden/.local/share/QGIS/QGIS3/profiles/default/python
/home/raden/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/media/sf_Shared/QGIS Projects/AoCmap-1
```

**Comment by radenblazed** [comment]
Heres the zip 
https://drive.google.com/file/d/1LGqaK-L0Rnbp0Rl8zAcb-rmMANq-NDHy/view?usp=sharing

**Comment by andreaordonselli** [comment]
You should pass me the svg icons, I can export the other layers well.

**Comment by radenblazed** [comment]
That was actually the problem. I had got some icon packs from https://plugins.qgis.org/styles/   ... using these icons caused it to throw those errors.

As for the Icons I used, it was a mix of the following:
Temaki Icon Packs: https://plugins.qgis.org/styles/types/Marker/?q=temaki
Maki Icon Packs: https://plugins.qgis.org/styles/types/Marker/?q=maki

Creating a map that does not contain those icons lets me export just fine.

**Comment by andreaordonselli** [comment]
How are you configuring the QGIS layer to display SVG icons?
Do you start from an xml icon package? Or do you provide the single svg icon? 
I think that is the problem, do a test by providing bulk svg icons.

**Comment by andreaordonselli** [comment]
Base64 encoded svg icons, so which are not from .svg files but from icon packages, are not supported in qgis2web, they will be supported soon [here](https://github.com/andreaordonselli/qgis2o.gis), I suggest you follow the updates

**Comment by andreaordonselli** [comment]
SVG base64 supported here https://github.com/andreaordonselli/qgis2o.gis/releases/tag/v2.25.0
