### ISSUE TITLE
SVG markers not working in qgis2web [lack of feedback]

### ISSUE THREAD

**Issue by GMusolino** [qgis2web/qgis2web#1115]
I'm using qgis2web 3.23.0. The SVG markers I've used in QGIS are not working in qgis2web. Does the Exception report below provide anyone with any idea how I can make this work?
Error on Export:
Exception in layer {Name of layer} with renderer CATEGORIZED: idx Categories Aboriginal Medical Service::Aboriginal Medical Service::MARKER SYMBOL (1 layers) color 0,0,0,255,rgb:0,0,0,1:1 General Practice::General Practice::MARKER SYMBOL (1 layers) color 0,0,0,255,rgb:0,0,0,1:1 : Traceback (most recent call last): File "{Name of file location}Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 52, in exportStyles useMapUnits) = categorized(defs, sln, layer, renderer, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "{Name of file location}Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 266, in categorized useMapUnits) = (getSymbolAsStyle(symbol, stylesFolder, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "{Name of file location}Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 618, in getSymbolAsStyle color = getRGBAColor(props["color"], alpha) ~~~~~^^^^^^^^^ KeyError: 'color' 

Works fine in QGIS (first image). Not working in qgis2web (second image)
![image](https://github.com/user-attachments/assets/5f21f8b9-6bce-40d6-a7b9-9f674c7b02fe)
![image](https://github.com/user-attachments/assets/e0560c04-2c16-4831-8867-b9e64f49f843)

**Comment by andreaordonselli** [comment]
Hi, now svg icons are better supported than before.
Can you send your project with data and svg icons so I can test?

**Comment by andreaordonselli** [comment]
closed due to lack of feedback

**Comment by iTigersX** [comment]
Hey @andreaordonselli , I have almost the same error I'm trying to export qgis map via qgis2web with OpenLayers option 

Traceback (most recent call last): File AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 52, in exportStyles useMapUnits) = categorized(defs, sln, layer, renderer, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 266, in categorized useMapUnits) = (getSymbolAsStyle(symbol, stylesFolder, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 652, in getSymbolAsStyle color = getRGBAColor(props["color"], alpha) ~~~~~^^^^^^^^^ KeyError: 'color' 

Seemingly there is success at the end, but a white page pops up. There is nothing on it

**Comment by andreaordonselli** [comment]
Can you send your project with data and svg icons so I can test?

**Comment by iTigersX** [comment]
> Can you send your project with data and svg icons so I can test?

I did it in a different way. Unfortunately, OpenLayers didn't work and the second option significantly changes the way the whole map appears. FELT plugin helped me there and posted website on their platform. We can close the topic for now.

**Comment by andreaordonselli** [comment]
I'm glad you solved it. You are probably using a symbology not supported by qgis2web, perhaps some SVG Base64 icons?

**Comment by iTigersX** [comment]
Honestly, I don't really know what the problem was, but fortunately it was solved
