### ISSUE TITLE
Leaflet export bug ?

### ISSUE THREAD

**Issue by kevindescampsfr** [qgis2web/qgis2web#1120]
Hello, It seems that the Leaflet export is not functional. The layers are not visible, only the basemap works. Other features do not work either, such as the layers list. I'm using the recommended version QGIS 3.38 with the latest version of qgis2web 3.24.

The openlayers export works.

**Comment by andreaordonselli** [comment]
Attach your project so I can watch the problem.

**Comment by kevindescampsfr** [comment]
[leafletbug_qgis2web.zip](https://github.com/user-attachments/files/18127614/leafletbug_qgis2web.zip)

**Comment by andreaordonselli** [comment]
Sorry but I don't have tui svg icons, I just see so many "?"

**Comment by kevindescampsfr** [comment]
[leafletbug_qgis2web_V2.zip](https://github.com/user-attachments/files/18128376/leafletbug_qgis2web_V2.zip)

Sorry, I forgot to attach the svg symbol. Here is a new version with the svg symbol. However, I encounter the same problem with a simple symbol.

**Comment by luxwarp** [comment]
Also get some errors when trying to use marker line

```
Traceback (most recent call last):
              File "/home/luxwarp/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 482, in previewMap
              preview_file = self.createPreview()
              ^^^^^^^^^^^^^^^^^^^^
              File "/home/luxwarp/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 444, in createPreview
              preview_file = writer.write(self.iface, dest_folder=utils.tempFolder()).index_file
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/luxwarp/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletWriter.py", line 94, in write
              self.preview_file = self.writeLeaflet(
              ^^^^^^^^^^^^^^^^^^
              File "/home/luxwarp/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletWriter.py", line 277, in writeLeaflet
              useOSMB) = writeVectorLayer(layer, safeLayerName,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/luxwarp/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletLayerScripts.py", line 125, in writeVectorLayer
              useShapes) = getLayerStyle(layer, safeLayerName, interactive,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/luxwarp/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletStyleScripts.py", line 63, in getLayerStyle
              pattern) = getSymbolAsStyle(cat.symbol(), markerFolder,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/luxwarp/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/leafletStyleScripts.py", line 180, in getSymbolAsStyle
              sl = symbol.symbolLayer(sl)
              ^^^^^^^^^^^^^^^^^^^^^^
             IndexError: 1
             ```

**Comment by andreaordonselli** [comment]
In the `scolaire` table, in the `Etablissement` field, there is a string contains the `"` double quotes, precisely the fid 5103 to be corrected to `Gemeinschaftsschule A.S. Puschkin` by deleting `"`

In the next release I will fix the code to handle such cases as well. 
Thanks for the report, let me know if you can export the project.

**Comment by kevindescampsfr** [comment]
Removing double quotes alone was not enough. However, I followed this path and also removed the commas and unconventional characters (eg: Šiaulių) and it works!

Many thanks for your help.

**Comment by andreaordonselli** [comment]
In version [3.25.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.25.0) the issue discussed in this thread is resolved. The update will soon be available in the QGIS plugin repository.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Thank you for using the plugin.

Best regards.
