### ISSUE TITLE
Export vector layer error for Processing Toolbox

### ISSUE THREAD

**Issue by Victoria-Glott** [qgis2web/qgis2web#972]
Hi, 
I am trying to automate the creation of webmaps but I get error messages when using the Processing toolbox with export vector layer. 

Traceback (most recent call last):
File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\qgis2webAlgorithm.py", line 412, in processAlgorithm
writer.write(iface, write_folder)
File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 91, in write
folder=dest_folder)
File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 138, in writeOL
mapSettings.destinationCrs().authid())
File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olLayerScripts.py", line 48, in writeLayersAndGroups
interactive[count], cluster, info,
IndexError: list index out of range

These are my input parameters: 

![image](https://user-images.githubusercontent.com/71123443/131355031-9ded489b-7b79-4837-85f1-ce106339cda6.png)

I didn't find any documentation on how to correctly fill out the above values , so I tried to copy values from the "Export to webmap" window. So I am not sure if it is something wrong with my input parameters or if it is a bug. Is this something you guys could help me with? :) Thanks

**Comment by mobessag** [comment]
Hello ! Did you finally managed to put the correct parameters ? Just like you, I can't find any clues on how to correcty fill the inputs.. Thanks :)
