### ISSUE TITLE
Error occuring while executing Python Code ("KeyError: 12")

### ISSUE THREAD

**Issue by denmur** [qgis2web/qgis2web#973]
When exporting a map (either as OpenLayers or Leaflet) I receive ' Python KeyError: 12' quite a lot.
There was issue before - #839 
Could you help me please?

Thanks in advance.
```
An error has occurred while executing Python code: 

KeyError: 12 
Traceback (most recent call last):
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 350, in saveMap
    feedback=self.feedback)
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 91, in write
    folder=dest_folder)
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 131, in writeOL
    popup, json, restrictToExtent, extent, feedback, matchCRS)
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 232, in exportLayers
    iface, extent, precision, crs, optimize)
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 245, in exportVector
    cleanLayer = writeTmpLayer(layer, restrictToExtent, iface, extent)
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 172, in writeTmpLayer
    uri = TYPE_MAP[layer.wkbType()]
KeyError: 12


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.10-Hannover Hannover, e5b665e952 

Python Path:
C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HTML_Generator-main
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\Users\...\AppData\Roaming\Python\Python37\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\...\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
U:...
```

**Comment by boesiii** [comment]
Are you able to provide your project file and a sample of your data?
